const ERROR_NOT_A_NUMBER = "ERROR_NOT_A_NUMBER";
const ERROR_POSITION_OUTSIDE_OF_BOARD = "ERROR_POSITION_OUTSIDE_OF_BOARD";
const ERROR_SPOT_IS_OCCUPIED = "ERROR_SPOT_IS_OCCUPIED";
const PLAYER_ONE = "X";

module.exports = {
  ERROR_NOT_A_NUMBER,
  ERROR_POSITION_OUTSIDE_OF_BOARD,
  ERROR_SPOT_IS_OCCUPIED,
  PLAYER_ONE,
};
